name: ${project.name}
version: ${project.version}
main: nl.svenar.powercore.bukkit.PowerCore
api-version: 1.13
authors: [svenar]
commands:
  powercore:
    description: PowerCore command
    aliases: [core, pcore]
  compass:
    description: Show a compass at the top of your screen
  time:
    description: Set the time
  day:
    description: Set the time to day
  night:
    description: Set the time to night
  sunset:
    description: Set the time to sunset
  sunrise:
    description: Set the time to sunrise
  noon:
    description: Set the time to noon
  midnight:
    description: Set the time to midnight
  weather:
    description: Set the weather
  sun:
    aliases: [clear]
    description: Set the weather to sunny
  rain:
    description: Set the weather to rainy
  thunder:
    aliases: [storm]
    description: Set the weather to thunder
  gamemode:
    aliases: [gm]
    description: Set the gamemode for yourself or another player
  survival:
    aliases: [gms]
    description: Set your gamemode to survival
  creative:
    aliases: [gmc]
    description: Set your gamemode to creative
  adventure:
    aliases: [gma]
    description: Set your gamemode to adventure
  spectator:
    aliases: [gmsp]
    description: Set your gamemode to spectator
  teleport:
    aliases: [tp]
    description: Teleport to a player
  offlineteleport:
    aliases: [offlinetp, otp]
    description: Teleport to an offline player
  top:
    description: Teleport to the highest block
  fly:
    description: Toggle fly mode on/off for yourself or another player
  speed:
    description: Set the walk/fly speed for yourself or another player
  speedinfo:
    description: Show the walk/fly speed for yourself or another player
  back:
    description: Teleport back to your previous location
  kick:
    description: Kick a player
  ban:
    description: Ban a player
  unban:
    aliases: [pardon]
    description: Unban a player
  seen:
    description: Show when a player was last online
  spawn:
    description: Teleport to the spawn location
  setspawn:
    description: Set the spawn location
  warp:
    description: Teleport to a warp location
  setwarp:
    description: Set a warp location
  spawnmob:
    description: Spawn a mob
  heal:
    description: Heal yourself or another player
  feed:
    description: Feed yourself or another player
  enderchest:
    aliases: [ec]
    description: Open the enderchest of yourself or another player
  invsee:
    description: Open the inventory of another player
  god:
    description: Toggle god mode on/off for yourself or another player
  burn:
    description: Set a player on fire
  smite:
    description: Strike a player with lightning
  whitelist:
    description: Manage the whitelist
  itemname:
    description: Set the name of an item
  itemlore:
    description: Set the lore of an item
permissions:
  powercore.compass:
    default: true
  powercore.compass.waypoints:
    default: op
  powercore.stats:
    default: op
  powercore.time:
    default: op
  powercore.weather:
    default: op
  powercore.gamemode.*:
    children:
      powercore.gamemode: true
    default: op
  powercore.gamemode:
    children:
      powercore.gamemode.survival: true
      powercore.gamemode.creative: true
      powercore.gamemode.adventure: true
      powercore.gamemode.spectator: true
    default: op
  powercore.gamemode.survival:
    default: op
  powercore.gamemode.creative:
    default: op
  powercore.gamemode.adventure:
    default: op
  powercore.gamemode.spectator: 
    default: op
  powercore.teleport.*:
    children:
      powercore.teleport: true
      powercore.teleport.offline: true
      powercore.teleport.top: true
    default: op
  powercore.teleport:
    default: op
  powercore.teleport.offline:
    default: op
  powercore.teleport.top:
    default: op
  powercore.fly:
    default: op
  powercore.speed:
    default: op
  powercore.back:
    default: true
  powercore.back.ondeath:
    default: op
  powercore.kick:
    default: op
  powercore.ban:
    default: op
  powercore.seen:
    default: op
  powercore.spawn:
    default: true
  powercore.spawn.set:
    default: op
  powercore.warp:
    default: true
  powercore.warp.set:
    default: op
  powercore.spawnmob:
    default: op
  powercore.heal:
    default: op
  powercore.feed:
    default: op
  powercore.enderchest:
    default: op
  powercore.enderchest.others:
    default: op
  powercore.invsee:
    default: op
  powercore.god:
    default: op
  powercore.burn:
    default: op
  powercore.smite:
    default: op
  powercore.whitelist:
    default: op
  powercore.itemname:
    default: op
  powercore.itemlore:
    default: op